### ISSUE TITLE
Handle refreshed tokens

### ISSUE THREAD

**Issue by JohNan** [JohNan/pyelectroluxgroup#4]
When the access token need to be refreshed, we use the refresh token to call an endpoint which will return a new access token and refresh token, which both will be used in subsequent requests.

The problem is that when you are about to use the cli again when the tokens has been refreshed you have no idea what tokens to start with. It's bad practice to log sensitive data so we need something else to store the tokens between subsequent runs. Or we can for now log the new tokens during the development process and find a way to notify the user implementing the library to store the new tokens, let that be an implementation that is up to the consumer of the library.

Make the token manager and abstract class that the consumer has to implement to take care of and store the new tokens.

**Comment by dezeroku** [comment]
In the CLI case I think we can add yet another subcommand `login` that would take the access keys and store them either directly on the drive (e.g. Bitwarden's `cli` does it this way) or in the user's keyring with something like [python-keyring](https://pypi.org/project/keyring/). The latter would be probably the preferred way and the hard drive used as a fallback.
Then the `list` and `command` subcommands could use (and freely update) the tokens stored locally, not requiring (or actually not even allowing) them to be passed through CLI arguments directly.

I'm not sure about the wider perspective of "the library" here though. Abstract classes sound like a good way to allow easy overrides by the consumers, but I still feel that a sensible default should be provided.

So in the end we could have:
* abstract classes that define the interface
* A concrete implementation using system keyring
* A concrete implementation using local filesystem storage

And we can let consumers choose if they want to use the prebuilts (that'd have to be explictly imported and passed as a parameter to some constructor) or define their own

**Comment by JohNan** [comment]
I like the suggestions. What I want to be able to achieve is to be able from the home assistant integration be able for the user to set the tokens during setup and keep them updated when they are refreshed.

So I guess the integration will subclass the abstract class to be able to hook into the config entry of the integration, and the cli and other consumers can choose to use their own implementation or any of the provided concrete classes.

I can try looking into this, but time is limited for me. You are welcome to implement it, but please let me know so we don't do double work 😊
